### ISSUE TITLE
Documentation not viewable due to HSTS error

### ISSUE THREAD

**Issue by kontur** [robotools/defcon#240]
It appears the documentation has a https error, e.g. Firefox gives users this:

```
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to defcon.robotools.dev because this website requires a secure connection.

What can you do about it?

defcon.robotools.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.
```

**Comment by belluzj** [comment]
Same problem in Chrome. Also, there is no workaround in the UI, no button to "go there anyway" so the website is effectively not viewable at all

![image](https://user-images.githubusercontent.com/3616772/59191701-24212880-8b78-11e9-8814-558be507c478.png)

**Comment by benkiel** [comment]
@belluzj @kontur Looking into this: it's odd that Chrome and FF are forcing a load into https, Safari does not. Will dig into.

**Comment by benkiel** [comment]
Ok, this is a setup issue with Read the Docs, our fault, working on fixing it. Sorry for the trouble!

**Comment by kontur** [comment]
The HSTS means the site is telling the browser to not even allow the user to overwrite and accept an insecure connection, if I remember correctly. Browsers show different levels of adherence to this, possibly? Anyway, good this is not an isolated issue and it got flagged instead of just being unavailable.

**Comment by benkiel** [comment]
This is fixed, thank you @typemytype

**Comment by kontur** [comment]
Can confirm it works for me, thanks for having a look at this :)
