### ISSUE TITLE
Anyway to convert UFO 2 to 3?

### ISSUE THREAD

**Issue by typoman** [robotools/defcon#246]
Hi I wasn't sure if this is the right title for this issue but I can't find the source of the following error while opening a UFO:

```
Exception ignored in: <function BaseObject.__del__ at 0x10f536d08>
Traceback (most recent call last):
  File "defcon/objects/base.py", line 56, in __del__
  File "defcon/objects/font.py", line 1125, in endSelfNotificationObservation
  File "defcon/objects/font.py", line 1148, in endSelfLayersNotificationObservation
  File "defcon/objects/font.py", line 1166, in _endSelfLayerNotificationObservation
  File "defcon/objects/base.py", line 123, in removeObserver
  File "defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
```

Could it be because defcon is reading a ufo 2 file? The ufos are normalized.

**Comment by typoman** [comment]
Thanks to @adrientetar, here is the code that converts all the UFO files underneath a folder to UFO 3.

```
from defcon import Font
import os
import logging
log = logging.getLogger(__name__)
logLevel = "DEBUG"
logging.basicConfig(level=logLevel, format="%(message)s")

path = "path/to/root/of/ufo_files"

for folder, _, files in os.walk(path):
	if folder.endswith(".ufo"):
		f = Font(folder)
		f.save(formatVersion=3)
		log.debug("Converted to UFO3:%s" % folder)
```

**Comment by anthrotype** [comment]
it's good you found a solution, but that doesn't explain why the error occurred in the first place, or how to reproduce in order to debug the issue.

**Comment by typoman** [comment]
I know, sorry! But I can't understand the error. The error is only occurring during a pytest in a module I'm developing. It doesn't happen when I run the module myself. Could it be that resources are closed at that moment?

**Comment by typoman** [comment]
btw converting the files doesn't resolve the error either, so the error is not relevant to the title of the issue. I can open another one?

**Comment by adrientetar** [comment]
Lol yeah that error is yikes. @typoman do you have the latest defcon? The line numbers in the traceback you posted don't seem to match the master on github.

**Comment by typoman** [comment]
I'm using the defcon from the main branch, installed using pip3:
```
Successfully installed defcon-0.6.1.dev0
```

Here the full error:
```
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: p/Tests, inifile: pytest.ini
collected 2 items                                                                                                                

this_test.py ..                                                                                                           [100%]

==================================================== 2 passed in 0.93 seconds ====================================================
Exception ignored in: <function BaseObject.__del__ at 0x1062337b8>
Traceback (most recent call last):
  File "python3.7/site-packages/defcon/objects/base.py", line 52, in __del__
  File "python3.7/site-packages/defcon/objects/font.py", line 1124, in endSelfNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1147, in endSelfLayersNotificationObservation
  File "python3.7/site-packages/defcon/objects/font.py", line 1165, in _endSelfLayerNotificationObservation
  File "python3.7/site-packages/defcon/objects/base.py", line 119, in removeObserver
  File "python3.7/site-packages/defcon/tools/notifications.py", line 110, in removeObserver
TypeError: 'NoneType' object is not callable
```

**Comment by anthrotype** [comment]
if you don't show the code that's calling defcon, we cannnot tell what it's doing by looking at the traceback.
I guess the removeObserver is being called unconditionally but no observer has been added...

**Comment by adrientetar** [comment]
I don't even get the exception, I mean line 100 of removeObserver is `observable = weakref.ref(observable)`, so `'NoneType' object is not callable` would mean that weakref.ref is None? 🤔
If so that's probably something happening during teardown of the python interpreter...

**Comment by benkiel** [comment]
Please do open a new issue on this, seems like it's a issue in the tests.
