### ISSUE TITLE
Improve notification debugging with observer identifier.

### ISSUE THREAD

**Issue by typesupply** [robotools/defcon#336]
Idea for assisting with debugging notifications: allow an optional string identifier during `addObserver`. The default value will be `None` so that there are no changes required in existing uses. There is no requirement that the string be unique. A reverse domain naming scheme is recommended, but there are no requirements for the structure of the string. An example:

```python
glyph.addObserver(
    observer=self,
    methodName="glyphChangedCallback",
    notification="Glyph.Changed",
    identifier="com.typesupply.GlyphNanny2.uiUpdates
}
```

`NotificationCenter` and all objects with an `addObserver` method will have this new argument and pass it to the underlying dispatcher. Within `NotificationCenter`, the identifiers will be stored in a new `_identifierRegistry` dict that has a similar structure to `_registry`.

There will be a method for searching for observations based on any of the values that may be passed during `addObserver`.

- `observable`
- `observer`
- `methodName`
- `notification`
- `identifier`

A value of `None` for any of these indicates that _all_ should be considered to match the value. In the case of `identifier`, strings will be matched using `fnmatch.fnmatchcase`.

```python
observations = dispatcher.findObservations("com.typesupply.GlyphNanny2.*")
```

The returned value will be a list of dictionaries with this format:

```python
[
    {
        observer=<...>
        observable=<...>
        methodName="..."
        notification="..."
        identifier="..."
    }
]
```

`NotificationCenter` and all objects with an `addObserver` method will have this new method. The implementation in `BaseObject` and its descendants will only return matches that pertain to the object through which the call was passed.

---

**This will be fully backwards compatible.** No code within the system for publishing notifications will be touched.

**Comment by typesupply** [comment]
cc @typemytype

**Comment by LettError** [comment]
Would that open up a way to remove all notifications that fit `"com.typesupply.GlyphNanny2.*"` ?
Common scenario for me is that something in the thing I'm working on breaks and the notifications are left running. Eventually making it necessary to start with a fresh application.

**Comment by typemytype** [comment]
that is the plan: make it easier and a lot more convenient to remove observers by a search on identifiers or observers or observales or even notifications

**Comment by typesupply** [comment]
> Would that open up a way to remove all notifications that fit "com.typesupply.GlyphNanny2.*" ?

Yes. Something like this would work:

```python
observations = obj.findObservations("com.typesupply.GlyphNanny2.*")
for observation in observations:
    observer = observation["observer"]
    notification = observation["notification"]
    obj.removeObserver(observer, notification)
```

Or globally:

```python
dispatcher = obj.dispatcher
observations = dispatcher.findObservations("com.typesupply.GlyphNanny2.*")
for observation in observations:
    observer = observation["observer"]
    observable = observation["observable"]
    notification = observation["notification"]
    dispatcher.removeObserver(observer, notification)
```
