### ISSUE TITLE
Contour._get_segments does not handle all off-curves contours

### ISSUE THREAD

**Issue by madig** [robotools/defcon#347]
This is more a corner case issue than anything dramatic, but if you have a contour with only off-curves, the method returns an empty list.

I rewrote the method at https://github.com/madig/HTLetterspacer/blob/33b9291/src/htletterspacer/core.py#L432-L460 from the code in PointToSegmentPen and wrote a property test at https://github.com/madig/HTLetterspacer/blob/reduce-better/tests/test_segmentation.py. It ensures that all invariants hold no matter what point list you throw at it. Maybe you can think of more invariants?

**Comment by typemytype** [comment]
should be a list with a single segment containing all the off curve points. (PR will follow)

**Comment by benkiel** [comment]
This is fixed, closing
