### ISSUE TITLE
It seems like `uni2010` might not be sorted by sortGlyphNames type="cannedDesign"

### ISSUE THREAD

**Issue by arrowtype** [robotools/defcon#350]
[These notes explain it in a little more detail](https://github.com/arrowtype/name-sans-roadmap/issues/34), but I had some trouble sorting fonts with defcon in a way that FontMake would build from.

## The Problem

I am making a build prep script to make font sources compatible for a variable font build. The script removes unique glyphs, removes guidelines, sorts all fonts, etc. 

However, I was surprised to run into a build error that said the fonts were sorted similarly, even if I sorted them with defcon right before running FontMake. 

```
INFO:fontTools.varLib:Merging OpenType Layout tables
fontmake: Error: ... 'Glyph order inconsistent across masters.', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```

Stranger still, if I instead sorted with a very similar script in RoboFont, the build _did_ work.

<details>
<summary><b>DefCon script</b> (Click to expand)</summary>

```python
"""
	Sort a font.
"""

import sys
from fontParts.world import *
from ufonormalizer import normalizeUFO

fontPath = sys.argv[1]

font = OpenFont(fontPath, showInterface=False)

newGlyphOrder = font.naked().unicodeData.sortGlyphNames(font.glyphOrder, sortDescriptors=[
                dict(type="cannedDesign", ascending=True, allowPseudoUnicode=True)])

font.glyphOrder = newGlyphOrder

font.save()
font.close()
```

</details>

<details>
<summary><b>RoboFont script</b> (Click to expand)</summary>

```python
from vanilla.dialogs import *
from mojo.UI import AskString

files =  getFile("Select files to sort", allowsMultipleSelection=True, fileTypes=["ufo"])

for file in files:
    font = OpenFont(file, showInterface=False)

    newGlyphOrder = font.naked().unicodeData.sortGlyphNames(font.templateGlyphOrder, sortDescriptors=[
                    dict(type="cannedDesign", ascending=True, allowPseudoUnicode=True)])

    font.templateGlyphOrder = newGlyphOrder

    font.save()
    font.close()
```

</details>

I did some print debugging in FontMake, and eventually found that `uni2010` seemed to be the one glyph out of order, after the DefCon ordering.

Once I added code to make sure `uni2010` (hyphen) was at the end of the glyph order in all fonts, the build succeeded. Before that, the orders were _almost_ the same, except for that one glyph name.

<details>
<summary><b>DefCon script that does work</b> (Click to expand)</summary>

```python
"""
	Sort a font, then place uni2010 last.
"""

import sys
from fontParts.world import *
from ufonormalizer import normalizeUFO

fontPath = sys.argv[1]

font = OpenFont(fontPath, showInterface=False)

newGlyphOrder = font.naked().unicodeData.sortGlyphNames(font.glyphOrder, sortDescriptors=[
                dict(type="cannedDesign", ascending=True, allowPseudoUnicode=True)])

if 'uni2010' in newGlyphOrder:
    newGlyphOrder.remove('uni2010')
    newGlyphOrder.append('uni2010')

font.glyphOrder = newGlyphOrder

font.save()
font.close()
```

</details>

And with that change, the variable font is building as expected. So, this makes me think three things are possible:

1. I might be misunderstanding how `cannedDesign` works (this is at least partly true, certainly), and it is working as intended/expected. (But then why might it be working differently in RoboFont? This is very weird, but I just tested it again to verify that I wasn’t imagining it).
1. Maybe DefCon misses the `uni2010` glyph in its sorting, for some reason.
1. Something in FontMake is messing up / not reading the order from DefCon, unless `uni2010` is placed last.

I’m working on a closed-source project, so I can’t share the build here, but I could email Tal/Ben/Frederik a zip of this, if that would be helpful/desired.

If I realize more about what is going wrong, or there is some other update, I will do my best to update this issue.

Thank you!

**Comment by typemytype** [comment]
Could you narrow down the problem to defcon only?  if you have a set of glyph names (with or without unicodes) the sorting must always be the same. Could you make an example script where glyphs like  `uni2010` are gone missing? 

silly questions first:
* are you sure all your fonts have the same glyph set (in RoboFont the template glyphs could "fake" real glyphs)
* does all those glyph in your fonts have the same unicode values



```python
# simple template test script
from defcon import Font

f = Font()

unicodes = [
    ord("a"), 
    ord("b"), 
    0x2010, 
    ord("-"), 
    ord("c")
]

for i in unicodes:
    n = f"uni{i:02X}"    
    g = f.newGlyph(n)
    g.unicode = i

newGlyphOrder = f.unicodeData.sortGlyphNames(list(f.keys()), sortDescriptors=[
                    dict(type="cannedDesign", ascending=True, allowPseudoUnicode=True)])
                    

print(f.glyphOrder)                
f.glyphOrder = newGlyphOrder
print(f.glyphOrder)
```

**Comment by arrowtype** [comment]
Hi Frederik, thanks for the response!

Just to verify: is your script there to show the sort of example what you would expect in response to `make an example script where glyphs like uni2010 are gone missing`? I assume that is the purpose, as that could go into an automated test. However, I think I may have found an issue, and it is perhaps in RoboFont (?) rather than in DefCon.

> are you sure all your fonts have the same glyph set (in RoboFont the template glyphs could "fake" real glyphs)

I am fairly sure they are, because the same build-prep script eliminates any glyphs that aren’t present and compatible in all fonts. It is possible that I could re-check this to be 100% certain, but the more obvious issue seems to be...

> does all those glyph in your fonts have the same unicode values

I thought they did, based on the following RoboFont script, as well as the info presented in the RF Inspector.

<details>
<summary><b>Screenshots</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/45946693/112050311-18251180-8b27-11eb-8cb3-b8fb3c7b645d.png)

![image](https://user-images.githubusercontent.com/45946693/112050521-56223580-8b27-11eb-8d18-d63410875198.png)

</details>

However, when I check _directly_ in the `.glif` files, I see that the "Text" styles _don’t_ have unicode values for `uni2010`.

Font that does have a Unicode value for `uni2010`:

![image](https://user-images.githubusercontent.com/45946693/112050768-9c779480-8b27-11eb-84a4-7a0a40161e14.png)

Font that does **not** appear to have a Unicode value for `uni2010`:

![image](https://user-images.githubusercontent.com/45946693/112050801-a3060c00-8b27-11eb-8d70-190eb49eae7e.png)

All three Text styles are like the latter example, where there is no `unicode` element in the glif XML.

So, perhaps the real issue is that RoboFont might be indicating that a unicode value is set, when it isn’t? Or, is there another piece of data that RoboFont is picking up on to report the Unicode as `(8208,)` for `uni2010` in all the fonts?

**Comment by typemytype** [comment]
oke, I see

what RoboFont does: whenever you set a `glyph.name` RoboFont tries to extract the unicode value from the glyph name if the name is explicit `uni<4-hex>` or `u<5-hex>`. I assume you created some of your `uni2010` glyphs in RoboFont and some outside so the unicode value wasnt touched .

When opening a UFO with a `uni<hex>` glyph RoboFont adds also the unicode value (but silently) which is confusing or even maybe a bug... 

This is also the reason why the order is different outside RoboFont...

**Comment by arrowtype** [comment]
Quick follow-up: once I manually added that XML to the Text sources, the font built successfully, with the simple DefCon sort and no added uni2010 sorting step.

> When opening a UFO with a uni<hex> glyph RoboFont adds also the unicode value (but silently) which is confusing or even maybe a bug...

This seems mostly good to me, but I would personally want it to save that unicode value to the `.glif` file itself, so i can be predictably handled between RoboFont and other tools (like DefCon & FontMake, etc). Otherwise, if RoboFont presents information as being in the UFO that isn’t actually/explicitly there, it might somewhat make me doubt _any_ information presented by RoboFont.

Anyway, thanks for helping me get to the bottom of this! Since this isn’t a DefCon issue, I’ll close this issue.

**Comment by typemytype** [comment]
I know, not good ...

RF should flag the document as changed while opening a UFO where RF adds a unicode value based on the `uni<hex>` name, so the user is aware

**Comment by arrowtype** [comment]
That seems like a solid approach! I do also end up opening fonts with RoboFont scripts and Vanilla, without showing the interface, to make batch edits or checks. I'm unsure whether it would be better to add the Unicode or not in the skip-interface scenario, but if it does add it there, it should also definitely save it in. Then again, the other acceptable route would be not auto-adding Unicodes without explicit user interaction (maybe a prompt on opening the UI?). It's hard to say what is best.
